concertconnect/urls.py
from django.contrib import admin
from django.urls import path, include
from concertconnect_app import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('concertconnect_app:register_profile')
urlpatterns = [
	
    path('', views.IndexView.as_view(), name='index'),
    path('', views.AboutView.as_view(), name='about'),
    path('concertconnect_app/', include('concertconnect_app.urls')),
 
    
    
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),

    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

concertconnect_app/urls.py
from django.urls import path
from concertconnect_app import views
from . import views
from django.urls import include, path
from django.conf.urls import url

app_name = 'concertconnect_app'

urlpatterns = [
	
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('concerts/', views.ConcertsView.as_view(), name='concerts'),
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.AddPageView.as_view(), name='add_page'),
    path('restricted/', views.RestrictedView.as_view(), name='restricted'),
    path('goto/', views.GotoView.as_view(), name='goto'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),
    path('search/', views.search_bar, name='search'),
 
]

concertconnect_app/models.py
from django.db import models

# Create your models here.
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    NAME_MAX_LENGTH = 128
    REVIEW_MAX_LENGTH = 500
    
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    venue_info = models.CharField(max_length = REVIEW_MAX_LENGTH, blank=True)
    likes = models.IntegerField(default=0)    
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
        
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    DES_MAX_LENGTH = 500
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=TITLE_MAX_LENGTH, unique = True)
    url = models.URLField()
    description = models.CharField (max_length = DES_MAX_LENGTH, blank=True)
    event_picture = models.CharField(max_length = URL_MAX_LENGTH, blank=True)
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    
class UserProfile(models.Model):
    TEXT_MAX_LENGTH = 500
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    concerts = models.CharField(max_length=TEXT_MAX_LENGTH, blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

concertconnect_app/forms.py
from django import forms
from concertconnect_app.models import Page, Category
from django.contrib.auth.models import User
from concertconnect_app.models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password','is_superuser',)
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('concerts', 'picture',)


# Earlier Chapters

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,
    help_text="Please enter the Venue's name.")
    venue_info= forms.CharField(max_length = Category.REVIEW_MAX_LENGTH, required=False, help_text = "Please Enter Venue info -- include Location")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)


    # An inline class to provide additional information on the form.
    class Meta:
    # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,help_text="Please enter the name of Event.")
    
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH,help_text="Please enter a URL for Event information.")
    
    description = forms.CharField(max_length=Page.DES_MAX_LENGTH,help_text="Please give a brief description of your Upcoming Event")
    
    event_picture = forms.CharField(max_length=Page.URL_MAX_LENGTH, help_text= "Please upload a picture.")
    
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
 # Here, we are hiding the foreign key.
 # we can either exclude the category field from the form,
        exclude = ('category',)
      
 # or specify the fields to include (don't include the category field).
 #fields = ('title', 'url', 'views')
    def clean(self):
        cleaned_data = self.cleaned_data
        event_picture = cleaned_data.get('event_picture')
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
          
        
        return cleaned_data

concertconnect_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import Http404
from datetime import datetime

from concertconnect_app.models import Category, Page, UserProfile

from concertconnect_app.forms import CategoryForm, PageForm
from concertconnect_app.forms import UserForm, UserProfileForm

from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from concertconnect_app.bing_search import run_query
from django.views import View
from django.contrib.auth.models import User


class ConcertsView(View):
    def get(self,request):

        category_list = Category.objects.order_by('name')
        page_list = Page.objects.order_by('title')

        context_dict = {}
        context_dict['categories'] = category_list
        context_dict['pages'] = page_list

        response = render(request, 'concertconnect_app/index.html', context=context_dict)

        visitor_cookie_handler(request)

        context_dict['visits'] = request.session['visits']

        return render(request, 'concertconnect_app/concerts.html', context_dict)



def search_denial():
    # Take the user back to the homepage.
    return redirect(reverse('concertconnect_app:restricted'))

###Chapter 13
def search_bar(request):
    result_list = []
    query = ''
    
    if request.method == 'POST':
        #Until You have made a key You will be sent to this page - if deleted without key, a 404 page shows
        return search_denial() # Delete when key is made 
        
        query = request.POST['query'].strip()

        if query:
            result_list = run_query(query)
    
    return render(request, 'concertconnect_app/search.html', {'result_list': result_list, 'query': query})




class IndexView(View):
    def get(self, request):
        category_list = Category.objects.order_by('-likes')[:5]
        page_list = Page.objects.order_by('-views')[:5]
        near_list = Category.objects.filter(venue_info__icontains= 'Glasgow')[:5]
        
        context_dict = {}
        context_dict['boldmessage']= 'Events up coming'
        context_dict['near_you'] = near_list
        context_dict['categories'] = category_list
        context_dict['pages'] = page_list

        # Obtain our Response object early so we can add cookie information.
        response = render(request, 'concertconnect_app/index.html', context=context_dict)

 
        visitor_cookie_handler(request)

        return render(request, 'concertconnect_app/index.html', context=context_dict)

class AboutView(View):
    """
    The about view, converted to a class-based approach. DM.
    """
    def get(self, request):
        context_dict = {}
        context_dict = {'name':'Group 4 Team A'} 
        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']

        return render(request, 'concertconnect_app/about.html', context_dict)

class ShowCategoryView(View):
    def create_context_dict(self, category_name_slug):
        context_dict = {}

        try:
            category = Category.objects.get(slug=category_name_slug)
            pages = Page.objects.filter(category=category).order_by('-views')

            context_dict['pages'] = pages
            context_dict['category'] = category
        except Category.DoesNotExist:
            context_dict['pages'] = None
            context_dict['category'] = None
        
        return context_dict
    
    def get(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'concertconnect_app/category.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        if request.method == 'POST':# delete both lines when you have key
            return search_denial() ##
        
        context_dict = self.create_context_dict(category_name_slug)
        query = request.POST['query'].strip()

        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query
        
        return render(request, 'concertconnect_app/category.html', context_dict)

class AddCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'concertconnect_app/add_category.html', {'form': form})
    
    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('concertconnect_app:index'))
        else:
            print(form.errors)
        
        return render(request, 'concertconnect_app/add_category.html', {'form': form})

class AddPageView(View):
    def get_category_name(self, category_name_slug):
   
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None
        
        return category
    
    @method_decorator(login_required)
    def get(self, request, category_name_slug):
        form = PageForm()
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('concertconnect_app:index'))
        
        context_dict = {'form': form, 'category': category}
        return render(request, 'concertconnect_app/add_page.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        form = PageForm(request.POST)
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('concertconnect_app:index'))
        
        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()

            return redirect(reverse('concertconnect_app:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)
        
        context_dict = {'form': form, 'category': category}
        return render(request, 'concertconnect_app/add_page.html', context=context_dict)

class RestrictedView(View):
    @method_decorator(login_required)
    def get(self, request):
        context_dict ={'bold': 'Restricted Page'}
        return render(request, 'concertconnect_app/restricted.html', context_dict)

class GotoView(View):
    def get(self, request):
        page_id = request.GET.get('page_id')

        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('concertconnect_app:index'))

        selected_page.views = selected_page.views + 1
        selected_page.save()

        return redirect(selected_page.url)

class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'concertconnect_app/profile_registration.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('concertconnect_app:index'))
        else:
            print(form.errors)
        
        context_dict = {'form': form}
        return render(request, 'concertconnect_app/profile_registration.html', context_dict)

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'concerts': user_profile.concerts,
                                'picture': user_profile.picture,})
        
        return (user, user_profile, form)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('concertconnect_app:index'))
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'concertconnect_app/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('concertconnect_app:index'))
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('concertconnect_app:profile',
                                    kwargs={'username': username}))
        else:
            print(form.errors)
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'concertconnect_app/profile.html', context_dict)

class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()

        return render(request, 'concertconnect_app/list_profiles.html', {'user_profile_list': profiles})

class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']

        try:

templates/concertconnect_app/add_category.html
{% extends 'concertconnect_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Concert
{% endblock %}

{% block body_block %}
 <div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Venue</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="category_form" method="post" action="{% url 'concertconnect_app:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Create Venue</button>
            <div class="p-5"></div>
        </form>
    </div>
</div>

{% endblock %}

templates/concertconnect_app/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load concertconnect_app_template_tags %}

<html>
    <head>
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            
            {% endblock %}
            <div>
            {% block sidebar_block %}
                <h3><b> Category List </b></h3>
                {% get_category_list category %}
            {% endblock %}
            </div>
            
            
        </div>
        <hr/>
        <div>
            <i><strong>Menu Bar</strong></i>            
            <ul>
            <!-- Outside the conditional statements, ALWAYS show -->
            <li><a href="{% url 'concertconnect_app:about' %}">About</a></li>
            
            <!-- Index -->
            <li><a href="{% url 'concertconnect_app:index' %}">Homepage</a></li>
                
            {% if user.is_authenticated %}
            <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'concertconnect_app:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change your Password</a></li>
                <li><a href="{% url 'concertconnect_app:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'concertconnect_app:index' %}">Logout</a></li>
        
            {% else %}
            <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
         
            </ul>
        </div>
    </body>
</html>

templates/concertconnect_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load concertconnect_app_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
       Concert Connect - {% block title_block %}{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
        <header>
            <nav class="navbar navbar navbar-dark fixed-top bg-dark p-0">
            
                <a class="navbar-brand p-3" href="{% url 'concertconnect_app:index' %}">
                    
                    
                  <div class="picture">
                      {% if user.is_authenticated and user_profile.picture %}
                      <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="59" height="55" alt="{{ selected_user.username }}'s profile image" /> 
                        {% else %}
                    <img src="{{ MEDIA_URL }}cat.jpg" width="59" height="55" alt="{{ selected_user.username }}'s profile image" /> 
                      {% endif %}
                    </div>
                <div class= "relative">Con<div class="static1">cert</div><div class="static2">nect</div></div>
                </a>
                
                           <div>
    <form class="form-inline" id="user-form" method="post" action="{% url 'concertconnect_app:search' %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Search" size="50" name="query" id="query" value="{{ query }}" />
        </div>

        <button class="btn btn-primary" type="submit" name="submit">Search</button>
    </form>
</div>
                
                
                
                
                <div id="button">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">Menu</span>
                </button>
                </div>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'concertconnect_app:index' %}">Home</a></li>
                    
                        <li class="nav-item "><a class="nav-link" href="{% url 'concertconnect_app:concerts' %}">Concerts</a></li>
                        {% if user.is_superuser %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'concertconnect_app:search' %}">Search</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'concertconnect_app:add_category' %}">Add Venue</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'concertconnect_app:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'concertconnect_app:list_profiles' %}">List Profiles</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/concertconnect_app/">Logout</a></li>
                        
                        {% elif user.is_authenticated and not user.is_superuser %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'concertconnect_app:restricted' %}">Restricted</a></li>
                         <li class="nav-item "><a class="nav-link" href="{% url 'concertconnect_app:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'concertconnect_app:list_profiles' %}">List Profiles</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/concertconnect_app/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here  </a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login/Sign up</a></li>
                        
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <br/>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2023 Concert Connect &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/jQuery.js" %}" crossorigin="anonymous"></script>
         <script src="/static/js/ajax.js"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/concertconnect_app/category.html
{% extends 'concertconnect_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
         <h1>{{ category.name }}</h1>
    {% else %}
        Unknown Category
    {% endif%}
{% endblock %}

{% block body_block %}

    {% if category %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">{{ category.name }}</h1>

            <!-- AJAX chapter likes button component. DM. -->
            <div>
                <strong>{{ category.views }}</strong>views<br/>
                <strong id="like_count">{{ category.likes }}</strong> likes
                {% if user.is_authenticated %}
                <button id="like_btn" data-categoryid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                    <span data-feather="fa fa-thumbs-up"></span>
                    Like Venue
                </button>
                {% endif %}
            </div>
        </div>
    </div>
<div id="page-listing"> <!-- For AJAX page adding functionality. -->
    {% if pages %}
    <ul>
        {% for page in pages %}
            <li>
                <a href="{% url 'concertconnect_app:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                <p> {{ page.description }} </p>
              <img src="{{ MEDIA_URL }}{{ page.event_picture }}" alt="Picture of a
{{ page.title }}", style="width:150px;height:150px;"/>
                {% if page.views > 1 %}
                    ({{ page.views }} views)
                {% elif page.views == 1 %}
                    ({{ page.views }} view)
                {% endif %}
            </li>
        {% endfor %}

            
    </ul>
</div>
    {% else %}
    <strong>No Events currently for this Venue.</strong>
    {% endif %}
    <br/>
    
    {% if user.is_superuser %}
        <a href="{% url 'concertconnect_app:add_page' category.slug %}">Add Event</a><br/>
    {% endif %}
    <br/>
    {% if user.is_authenticated %}

    <div>
        <form class="form-inline" id="user-form" method="post" action="{% url 'concertconnect_app:show_category' category.slug %}">
            {% csrf_token %}
    
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" placeholder="Search of Concerts" id="query" value="{{ query }}" />
            </div>
    
            <button class="btn btn-success" type="submit" name="submit" >Search</button>
        </form>
    </div>
    <div>
        {% if result_list %}
        <h2>Results</h2>
    
        <div class="list-group">
        {% for result in result_list %}
            <div class="list-group-item">
                <h3 class="list-group-item-heading">
                    <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
                </h3>
                <p class="list-group-item-text">
                    {{ result.summary|safe|escape }}
                </p>
            </div>
        {% endfor %}
        </div>
        {% endif %}
    </div>
    {% endif %}


    {% else %}
        The specified category does not exist.
    {% endif %}

{% endblock %}
    

templates/concertconnect_app/page_listing.html
{% if pages %}
<ul>
    {% for page in pages %}
    <li>
        <a href="{% url 'concertconnect_app:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
        {% if page.views > 1 %}
            ({{ page.views }} views)
        {% elif page.views == 1 %}
            ({{ page.views}} views)
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<strong>No concerts currently in category.</strong>
{% endif %}

templates/concertconnect_app/search.html
{% extends 'concertconnect_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Search for Upcoming Concerts</h1>
    </div>
</div>
<div>
    <form class="form-inline" id="user-form" method="post" action="{% url 'concertconnect_app:search' %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" id="query" placeholder="Search with us!" value="{{ query }}" />
        </div>

        <button class="btn btn-primary" type="submit" name="submit">Search</button>
    </form>
</div>
<div>
    {% if result_list %}
    <h2>Results</h2>

    <div class="list-group">
    {% for result in result_list %}
        <div class="list-group-item">
            <h3 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
            </h3>
            <p class="list-group-item-text">
                {{ result.summary|safe|escape }}
            </p>
        </div>
    {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}