concertconnect/urls.py
from django.contrib import admin
from django.urls import path, include
from concertconnect_app import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('concertconnect_app:register_profile')
urlpatterns = [
	
    path('', views.IndexView.as_view(), name='index'),
    path('', views.AboutView.as_view(), name='about'),
    path('concertconnect_app/', include('concertconnect_app.urls')),
 
    
    
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),

    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

concertconnect_app/urls.py
from django.urls import path
from concertconnect_app import views
from . import views
from django.urls import include, path
from django.conf.urls import url

app_name = 'concertconnect_app'

urlpatterns = [
	
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('concerts/', views.ConcertsView.as_view(), name='concerts'),
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.AddPageView.as_view(), name='add_page'),
    path('restricted/', views.RestrictedView.as_view(), name='restricted'),
    path('goto/', views.GotoView.as_view(), name='goto'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),
    path('search/', views.search_bar, name='search'),
 
]

templates/concertconnect/add_category.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
       
        <h1>Add a Category</h1>
        <div>
             <form id="category_form" method="post" action="{% url 'concertconnect:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        </div>

{% endblock %}

templates/concertconnect/add_page.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
        <h1>Add a Page to {{ category.name }}</h1>

        <div>
            <form id="add_page_form" method="post" action="{% 'concertconnect:category' category.slug }">
<!--                protects amd secures the HTTP POST request-->
                {% csrf_token %}
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Add Page" />
            </form>
        </div>

{% endblock %}

templates/concertconnect/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head>
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            
            {% endblock %}
            <div>
            {% block sidebar_block %}
                <h3><b> Category List </b></h3>
                {% get_category_list category %}
            {% endblock %}
            </div>
            
            
        </div>
        <hr/>
        <div>
            <i><strong>Menu Bar</strong></i>            
            <ul>
            <!-- Outside the conditional statements, ALWAYS show -->
            <li><a href="{% url 'concertconnect:about' %}">About</a></li>
                
            <!-- Index -->
            <li><a href="{% url 'concertconnect:index' %}">Homepage</a></li>
                
            {% if user.is_authenticated %}
            <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'concertconnect:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'concertconnect:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'concertconnect:logout' %}">Logout</a></li>
        
            {% else %}
            <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'concertconnect:register' %}">Sign Up</a></li>
                <li><a href="{% url 'concertconnect:login' %}">Login</a></li>
            {% endif %}
         
            </ul>
        </div>
    </body>
</html>

templates/concertconnect/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li>
        <strong>
            <a href="{% url 'concertconnect:show_category' c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
        {% else %}
        <li>
            <a href="{% url 'concertconnect:show_category' c.slug %}">{{ c.name }}</a>
        </li>
        {% endif %}
    {% endfor %}
    
    
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/concertconnect/category.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
         <h1>{{ category.name }}</h1>
    {% else %}
        Unknown Category
    {% endif%}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>        
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}
        <br/>
        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br/>
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}

{% endblock %}
    

templates/concertconnect/chosenconcert.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
   Chosen Concerts
{% endblock %}

{% block body_block %}
    <h1>Concerts {{ name }} might go to:</h1>
    <div>
       <strong>{{ name }}</strong>.
        <br/>  
        <br/>
    </div>

    <div>
        <img style="width:300px;height:300px;", src="{% static 'images/rango-close-up.jpg' %}"
alt="Picture of our beloved mascot: Rango" /> 
    </div>
    
    <div>
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a
Cat.", style="width:100px;height:100px;"/><br>
    From National Geographic.
    <a href=" https://www.nationalgeographic.com/animals/mammals/facts/domestic-cat" target="_blank">Link</a><br/>
    </div>
    
    
    <div><p>Visits: {{ visits }}</p> </div>
{% endblock %}

templates/concertconnect/concerts.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Concerts
{% endblock %}

{% block body_block %}
    <h1>Welcome to the Concert page</h1>
    <div>
        This has been put together by <strong>{{ name }}</strong>.
        <br/>  
        <br/>
    </div>

    <div>
        <img style="width:100px;height:100px;", src="{% static 'images/rango-close-up.jpg' %}"
alt="Picture of our beloved mascot: Rango" /> 
    </div>
    
    <div>
    <h2>Popular Venues</h2>
        
    <img src="{{ MEDIA_URL }} the-sse-hydro.jpg" alt="Picture of the SSE Hydro", style="width:400px;height:400px;"/><br>
    From tripadvisor.com <br>
    
    <img src="{{ MEDIA_URL }} O2_arena.jpg" alt="Picture of the O2 arena", style="width:400px;height:400px;"/><br>
    From Buro Happold
        
    <a href=" https://www.burohappold.com/projects/up-at-the-o2/" target="_blank">Link</a><br/>
    </div>
    
    
    <div><p>Visits: {{ visits }}</p> </div>
{% endblock %}

templates/concertconnect/index.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %} 

{% block title_block %}
        Homepage 
{% endblock %}
{% block body_block %}

    <h1>Concert Buddy says...</h1>
    
    <div>
       {% if user.is_authenticated %}
        Welcome <i style=" color:blueviolet"><b>{{ user.username }}!</b></i>
        {% else %}
<!--        Follow wireframe -->
        {% endif %}
        <br/>
        <br/>
        <strong>{{ boldmessage }}</strong><br/>    
      
    </div>
    
    
    
    <div>
        <h2>Most Liked Categories</h2>
    {% if categories %}
     <ul>
        {% for category in categories %}
     <li><a href="/concertconnect/category/{{ category.slug }}"></a>{{ category.name }}</li>
        {% endfor %}
     </ul>
    {% else %}
            <strong>There are no categories present.</strong>
    {% endif %}
    </div>
    
    
    <br><br/>
    
    <div>
        <h2>Most Viewed Pages</h2>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
    </div>
    
    
    <div>
        <img style="width:200px;height:200px;", src="{% static 'images/rango-close-up.jpg' %}"
alt="Picture of our beloved mascot: Rango" /> 
    </div>
        
    
{% endblock %}

templates/concertconnect/login.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1><b>Login to Concert Connect!</b></h1>
<br/>

<form id="login_form" method="post" action="{% url 'concertconnect:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50"/>
        <br />
        Password: <input type="password" name="password" value="" size="50"/>
        <br />
        <input type="submit" value="submit"/>

</form>
{% endblock %}

templates/concertconnect/register.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="{% url 'concertconnect:index' %}"><b>Return to the homepage.</b></a><br />

{% else %}
<strong>Register here!</strong><br />
<form id="user_form" method="post" action="{% url 'concertconnect:register' %}" enctype="multipart/form-data">
<!--above Sending package and data -->
    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/concertconnect/restricted.html
{% extends 'concertconnect/base.html' %}
{% load staticfiles %}

{% block title_block %}
   <strong>{{ bold }}</strong><br/> 
{% endblock %}

{% block body_block %}
    <p style="color:crimson"><strong><em>
        You should not be here please return to the previous page, homepage or sign in.
        </em></strong>
    </p>
{% endblock %}